### ISSUE TITLE
Aufrufe tracen (Spring Sleuth)

### ISSUE THREAD

**Issue by jdufner** [jdufner/microservice#10]
# Als Zuschauer der Demo möchte ich einzelne Aufrufe in der Architektur / Infrastruktur verfolgen können, weil ich wissen möchte welche Microservices beteiligt sind.

## Integriere Spring Sleuth
* https://cloud.spring.io/spring-cloud-sleuth/

**Comment by bfassbender** [comment]
Added with Pull Request #27

**Comment by bfassbender** [comment]
Please peer review.
