### ISSUE TITLE
Do we really need @EnableHystrixDashboard in primes and hello-world?

### ISSUE THREAD

**Issue by bfassbender** [jdufner/microservice#26]
Currently primes and hello-world each carry the annotation.
I'd say we can remove this as we have the monitor app for the dashboard.

**Comment by jdufner** [comment]
I agree. I'll remove branch 06_Hystrix-Dashboard_aktiviert and merge branches 05_Circuit-Breaker_eingebaut and 07_Monitor_eingebaut together.

**Comment by jdufner** [comment]
I decided not to merge 05_Circuit-Breaker and 07_Monitor, because they are too different.

**Comment by bfassbender** [comment]
Did you remove the annotations in all branches manually then?

**Comment by jdufner** [comment]
Thank you for review. I merged the change from lower branches to upper branches, but I stopped unintentionally at branch 09.

**Comment by jdufner** [comment]
Done in all branches.
